### ISSUE TITLE
Org.build_host_link ignores subdomain set in Org

### ISSUE THREAD

**Issue by evansmurithi** [rapidpro/dash#122]
## Issue

When calling `build_host_link` in `Org` model, e.g. in `Invitation.send_email`, the subdomain of the organization is ignored.

## Steps to reproduce

1. Create an organization with a subdomain.
2. Ensure `settings.HOSTNAME == 'subdomain.domain'` and `settings.SESSION_COOKIE_SECURE == True`
3. Calling `org.build_host_link()` returns `http://domain`

## Expected results

Calling `org.build_host_link()` should return `https://subdomain.domain`, note the prefix is "https" and not "http". Also, the subdomain is included in the link.

**Comment by norkans7** [comment]
1. `settings.HOSTNAME == "domain"`
2. `subdomain` is set on the Org object in the field subdomain 
3. Org object should not have domain field set unless you use a custom domain instead of a subdomain on the domain set in step 1)


Probably the tests can clarify more 
https://github.com/rapidpro/dash/blob/d1fd5632104f634791c3deeb656eb0d34d814061/test_runner/tests.py#L505-L533
